-- SkipQ MVP database schema, RLS, and trusted transactional functions.
-- Source of truth: docs/database-design.md

create extension if not exists pgcrypto;

create type public.role_name as enum ('customer', 'shop_staff', 'admin');
create type public.approval_status as enum ('PENDING', 'APPROVED', 'REJECTED', 'SUSPENDED');
create type public.order_status as enum ('PAYMENT_PENDING', 'PLACED', 'PREPARING', 'READY', 'COLLECTED', 'CANCELLED');
create type public.payment_method as enum ('CASH', 'ONLINE');
create type public.payment_provider as enum ('SSLCOMMERZ');
create type public.payment_status as enum ('PENDING', 'PAID', 'FAILED', 'CANCELLED', 'EXPIRED', 'REFUND_PENDING', 'REFUNDED');
create type public.refund_status as enum ('NOT_REQUIRED', 'PENDING', 'REFUNDED', 'FAILED');
create type public.reservation_status as enum ('ACTIVE', 'CONSUMED', 'RELEASED', 'EXPIRED');

create table public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  display_name text,
  phone text unique,
  avatar_url text,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint profiles_display_name_not_blank check (display_name is null or btrim(display_name) <> ''),
  constraint profiles_phone_not_blank check (phone is null or btrim(phone) <> '')
);

create table public.roles (
  id smallint generated by default as identity primary key,
  name public.role_name not null unique,
  description text,
  created_at timestamptz not null default now()
);

create table public.user_roles (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references public.profiles(id) on delete cascade,
  role_id smallint not null references public.roles(id) on delete restrict,
  is_active boolean not null default true,
  assigned_by uuid references public.profiles(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.universities (
  id uuid primary key default gen_random_uuid(),
  name text not null unique,
  slug text not null unique,
  is_active boolean not null default true,
  created_by uuid references public.profiles(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint universities_name_not_blank check (btrim(name) <> ''),
  constraint universities_slug_not_blank check (btrim(slug) <> '')
);

create table public.cafeterias (
  id uuid primary key default gen_random_uuid(),
  university_id uuid not null references public.universities(id) on delete restrict,
  name text not null,
  slug text not null,
  is_active boolean not null default true,
  approval_status public.approval_status not null default 'PENDING',
  created_by uuid references public.profiles(id) on delete set null,
  approved_by uuid references public.profiles(id) on delete set null,
  approved_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint cafeterias_name_not_blank check (btrim(name) <> ''),
  constraint cafeterias_slug_not_blank check (btrim(slug) <> ''),
  unique (university_id, name),
  unique (university_id, slug)
);

create table public.shops (
  id uuid primary key default gen_random_uuid(),
  cafeteria_id uuid not null references public.cafeterias(id) on delete restrict,
  owner_profile_id uuid references public.profiles(id) on delete set null,
  name text not null,
  slug text not null,
  description text,
  logo_path text,
  is_active boolean not null default true,
  approval_status public.approval_status not null default 'PENDING',
  created_by uuid references public.profiles(id) on delete set null,
  approved_by uuid references public.profiles(id) on delete set null,
  approved_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint shops_name_not_blank check (btrim(name) <> ''),
  constraint shops_slug_not_blank check (btrim(slug) <> ''),
  unique (cafeteria_id, name),
  unique (cafeteria_id, slug)
);

create table public.shop_staff_memberships (
  id uuid primary key default gen_random_uuid(),
  shop_id uuid not null references public.shops(id) on delete cascade,
  user_id uuid not null references public.profiles(id) on delete cascade,
  is_active boolean not null default true,
  assigned_by uuid references public.profiles(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.menu_items (
  id uuid primary key default gen_random_uuid(),
  shop_id uuid not null references public.shops(id) on delete cascade,
  name text not null,
  description text,
  price numeric(12,2) not null,
  image_path text,
  stock_quantity integer not null default 0,
  max_quantity_per_order integer not null,
  is_manually_available boolean not null default true,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint menu_items_name_not_blank check (btrim(name) <> ''),
  constraint menu_items_price_non_negative check (price >= 0),
  constraint menu_items_stock_non_negative check (stock_quantity >= 0),
  constraint menu_items_max_quantity_positive check (max_quantity_per_order > 0)
);

create table public.orders (
  id uuid primary key default gen_random_uuid(),
  order_number text not null unique,
  customer_id uuid not null references public.profiles(id) on delete restrict,
  university_id uuid not null references public.universities(id) on delete restrict,
  cafeteria_id uuid not null references public.cafeterias(id) on delete restrict,
  shop_id uuid not null references public.shops(id) on delete restrict,
  status public.order_status not null,
  payment_method public.payment_method not null,
  total_amount numeric(12,2) not null,
  currency char(3) not null default 'BDT',
  cancelled_at timestamptz,
  cancelled_by uuid references public.profiles(id) on delete set null,
  cancellation_reason text,
  inventory_restored boolean not null default false,
  collected_at timestamptz,
  collected_by uuid references public.profiles(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint orders_total_non_negative check (total_amount >= 0),
  constraint orders_cancelled_metadata check (
    (status <> 'CANCELLED') or (cancelled_at is not null and cancelled_by is not null and btrim(coalesce(cancellation_reason, '')) <> '')
  ),
  constraint orders_collected_metadata check (
    (status <> 'COLLECTED') or (collected_at is not null and collected_by is not null)
  )
);

create table public.order_items (
  id uuid primary key default gen_random_uuid(),
  order_id uuid not null references public.orders(id) on delete cascade,
  menu_item_id uuid not null references public.menu_items(id) on delete restrict,
  item_name_snapshot text not null,
  quantity integer not null,
  unit_price_snapshot numeric(12,2) not null,
  line_total_snapshot numeric(12,2) not null,
  created_at timestamptz not null default now(),
  constraint order_items_name_snapshot_not_blank check (btrim(item_name_snapshot) <> ''),
  constraint order_items_quantity_positive check (quantity > 0),
  constraint order_items_unit_price_non_negative check (unit_price_snapshot >= 0),
  constraint order_items_line_total_valid check (line_total_snapshot = quantity * unit_price_snapshot)
);

create table public.order_status_events (
  id uuid primary key default gen_random_uuid(),
  order_id uuid not null references public.orders(id) on delete cascade,
  previous_status public.order_status,
  new_status public.order_status not null,
  actor_user_id uuid references public.profiles(id) on delete set null,
  reason text,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  constraint order_status_events_reason_for_cancel check (new_status <> 'CANCELLED' or btrim(coalesce(reason, '')) <> '')
);

create table public.payment_attempts (
  id uuid primary key default gen_random_uuid(),
  order_id uuid not null references public.orders(id) on delete cascade,
  method public.payment_method not null,
  provider public.payment_provider,
  provider_channel text,
  status public.payment_status not null default 'PENDING',
  amount numeric(12,2) not null,
  currency char(3) not null default 'BDT',
  transaction_ref text not null unique,
  gateway_session_id text unique,
  gateway_transaction_id text unique,
  gateway_metadata jsonb not null default '{}'::jsonb,
  paid_at timestamptz,
  failed_at timestamptz,
  cancelled_at timestamptz,
  expired_at timestamptz,
  refund_status public.refund_status not null default 'NOT_REQUIRED',
  refund_reference text,
  refund_metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint payment_attempts_amount_non_negative check (amount >= 0),
  constraint payment_attempts_online_provider check ((method = 'ONLINE' and provider = 'SSLCOMMERZ') or (method = 'CASH' and provider is null)),
  constraint payment_attempts_paid_timestamp check (status <> 'PAID' or paid_at is not null)
);

create table public.inventory_reservations (
  id uuid primary key default gen_random_uuid(),
  menu_item_id uuid not null references public.menu_items(id) on delete cascade,
  order_id uuid not null references public.orders(id) on delete cascade,
  payment_attempt_id uuid references public.payment_attempts(id) on delete cascade deferrable initially deferred,
  quantity integer not null,
  status public.reservation_status not null default 'ACTIVE',
  expires_at timestamptz not null,
  consumed_at timestamptz,
  released_at timestamptz,
  expired_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint inventory_reservations_quantity_positive check (quantity > 0),
  constraint inventory_reservations_expiry_valid check (expires_at > created_at),
  constraint inventory_reservations_consumed_timestamp check (status <> 'CONSUMED' or consumed_at is not null),
  constraint inventory_reservations_released_timestamp check (status <> 'RELEASED' or released_at is not null),
  constraint inventory_reservations_expired_timestamp check (status <> 'EXPIRED' or expired_at is not null)
);

create table public.collection_codes (
  id uuid primary key default gen_random_uuid(),
  order_id uuid not null unique references public.orders(id) on delete cascade,
  token_hash text not null unique,
  expires_at timestamptz,
  used_at timestamptz,
  validated_by uuid references public.profiles(id) on delete set null,
  created_at timestamptz not null default now(),
  constraint collection_codes_token_hash_not_blank check (btrim(token_hash) <> '')
);

create unique index user_roles_one_active_role on public.user_roles(user_id, role_id) where is_active;
create unique index shop_staff_one_active_membership on public.shop_staff_memberships(shop_id, user_id) where is_active;
create unique index payment_attempts_one_paid_per_order on public.payment_attempts(order_id) where status = 'PAID';

create index user_roles_user_active_idx on public.user_roles(user_id, is_active);
create index user_roles_role_active_idx on public.user_roles(role_id, is_active);
create index shop_staff_memberships_user_active_idx on public.shop_staff_memberships(user_id, is_active);
create index shop_staff_memberships_shop_active_idx on public.shop_staff_memberships(shop_id, is_active);
create index cafeterias_university_public_idx on public.cafeterias(university_id, is_active, approval_status);
create index shops_cafeteria_public_idx on public.shops(cafeteria_id, is_active, approval_status);
create index menu_items_shop_public_idx on public.menu_items(shop_id, is_active, is_manually_available);
create index orders_customer_created_idx on public.orders(customer_id, created_at desc);
create index orders_customer_status_idx on public.orders(customer_id, status);
create index orders_shop_status_created_idx on public.orders(shop_id, status, created_at desc);
create index orders_shop_created_idx on public.orders(shop_id, created_at desc);
create index order_items_order_idx on public.order_items(order_id);
create index order_status_events_order_created_idx on public.order_status_events(order_id, created_at);
create index payment_attempts_order_created_idx on public.payment_attempts(order_id, created_at desc);
create index inventory_reservations_menu_status_idx on public.inventory_reservations(menu_item_id, status);
create index inventory_reservations_order_idx on public.inventory_reservations(order_id);
create index inventory_reservations_payment_attempt_idx on public.inventory_reservations(payment_attempt_id);
create index inventory_reservations_active_expiry_idx on public.inventory_reservations(status, expires_at) where status = 'ACTIVE';
create index collection_codes_used_at_idx on public.collection_codes(used_at);

create or replace function public.set_updated_at()
returns trigger
language plpgsql
set search_path = public, pg_temp
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

create trigger profiles_set_updated_at before update on public.profiles for each row execute function public.set_updated_at();
create trigger user_roles_set_updated_at before update on public.user_roles for each row execute function public.set_updated_at();
create trigger universities_set_updated_at before update on public.universities for each row execute function public.set_updated_at();
create trigger cafeterias_set_updated_at before update on public.cafeterias for each row execute function public.set_updated_at();
create trigger shops_set_updated_at before update on public.shops for each row execute function public.set_updated_at();
create trigger shop_staff_memberships_set_updated_at before update on public.shop_staff_memberships for each row execute function public.set_updated_at();
create trigger menu_items_set_updated_at before update on public.menu_items for each row execute function public.set_updated_at();
create trigger orders_set_updated_at before update on public.orders for each row execute function public.set_updated_at();
create trigger payment_attempts_set_updated_at before update on public.payment_attempts for each row execute function public.set_updated_at();
create trigger inventory_reservations_set_updated_at before update on public.inventory_reservations for each row execute function public.set_updated_at();

insert into public.roles(name, description) values
  ('customer', 'Customer users who place and track orders'),
  ('shop_staff', 'Shop/Sales Terminal staff who operate assigned shops'),
  ('admin', 'Administrators who manage system entities and approvals')
on conflict (name) do update set description = excluded.description;

create or replace function public.has_role(p_user_id uuid, p_role public.role_name)
returns boolean
language sql
stable
security definer
set search_path = public, pg_temp
as $$
  select exists (
    select 1
    from public.user_roles ur
    join public.roles r on r.id = ur.role_id
    join public.profiles p on p.id = ur.user_id
    where ur.user_id = p_user_id
      and r.name = p_role
      and ur.is_active
      and p.is_active
  );
$$;

create or replace function public.is_admin(p_user_id uuid)
returns boolean
language sql
stable
security definer
set search_path = public, pg_temp
as $$
  select public.has_role(p_user_id, 'admin');
$$;

create or replace function public.is_active_shop_staff(p_user_id uuid, p_shop_id uuid)
returns boolean
language sql
stable
security definer
set search_path = public, pg_temp
as $$
  select public.has_role(p_user_id, 'shop_staff') and exists (
    select 1
    from public.shop_staff_memberships ssm
    join public.profiles p on p.id = ssm.user_id
    where ssm.user_id = p_user_id
      and ssm.shop_id = p_shop_id
      and ssm.is_active
      and p.is_active
  );
$$;

create or replace function public.make_order_number()
returns text
language plpgsql
volatile
set search_path = public, pg_temp
as $$
declare
  v_order_number text;
begin
  loop
    v_order_number := 'SKQ-' || upper(substr(encode(gen_random_bytes(6), 'hex'), 1, 10));
    exit when not exists (select 1 from public.orders where order_number = v_order_number);
  end loop;
  return v_order_number;
end;
$$;

create or replace function public.hash_collection_token(p_token text)
returns text
language sql
immutable
set search_path = public, pg_temp
as $$
  select encode(digest(p_token, 'sha256'), 'hex');
$$;

create or replace function public.active_reserved_quantity(p_menu_item_id uuid)
returns integer
language sql
stable
security definer
set search_path = public, pg_temp
as $$
  select coalesce(sum(quantity), 0)::integer
  from public.inventory_reservations
  where menu_item_id = p_menu_item_id
    and status = 'ACTIVE'
    and expires_at > now();
$$;

create or replace function public.create_collection_code(p_order_id uuid)
returns text
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  v_token text;
begin
  v_token := encode(gen_random_bytes(32), 'base64url');
  insert into public.collection_codes(order_id, token_hash)
  values (p_order_id, public.hash_collection_token(v_token));
  return v_token;
end;
$$;

create or replace function public.create_cash_order(p_shop_id uuid, p_items jsonb)
returns jsonb
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  v_user_id uuid := auth.uid();
  v_order_id uuid := gen_random_uuid();
  v_order_number text := public.make_order_number();
  v_total numeric(12,2) := 0;
  v_item jsonb;
  v_menu public.menu_items%rowtype;
  v_qty integer;
  v_uni uuid;
  v_cafe uuid;
  v_token text;
begin
  if v_user_id is null or not public.has_role(v_user_id, 'customer') then
    raise exception 'Only authenticated customers can create orders';
  end if;
  if jsonb_typeof(p_items) <> 'array' or jsonb_array_length(p_items) = 0 then
    raise exception 'Order must contain at least one item';
  end if;

  select c.university_id, s.cafeteria_id into v_uni, v_cafe
  from public.shops s
  join public.cafeterias c on c.id = s.cafeteria_id
  join public.universities u on u.id = c.university_id
  where s.id = p_shop_id and s.is_active and s.approval_status = 'APPROVED'
    and c.is_active and c.approval_status = 'APPROVED' and u.is_active;
  if v_uni is null then raise exception 'Shop is not orderable'; end if;

  insert into public.orders(id, order_number, customer_id, university_id, cafeteria_id, shop_id, status, payment_method, total_amount)
  values (v_order_id, v_order_number, v_user_id, v_uni, v_cafe, p_shop_id, 'PLACED', 'CASH', 0);

  for v_item in select * from jsonb_array_elements(p_items) loop
    v_qty := (v_item->>'quantity')::integer;
    select * into v_menu from public.menu_items where id = (v_item->>'menu_item_id')::uuid and shop_id = p_shop_id for update;
    if not found or not v_menu.is_active or not v_menu.is_manually_available then raise exception 'Menu item is unavailable'; end if;
    if v_qty is null or v_qty <= 0 or v_qty > v_menu.max_quantity_per_order then raise exception 'Invalid item quantity'; end if;
    if v_menu.stock_quantity - public.active_reserved_quantity(v_menu.id) < v_qty then raise exception 'Insufficient stock'; end if;
    update public.menu_items set stock_quantity = stock_quantity - v_qty where id = v_menu.id;
    insert into public.order_items(order_id, menu_item_id, item_name_snapshot, quantity, unit_price_snapshot, line_total_snapshot)
    values (v_order_id, v_menu.id, v_menu.name, v_qty, v_menu.price, v_qty * v_menu.price);
    v_total := v_total + (v_qty * v_menu.price);
  end loop;

  update public.orders set total_amount = v_total where id = v_order_id;
  insert into public.payment_attempts(order_id, method, status, amount, transaction_ref, paid_at)
  values (v_order_id, 'CASH', 'PAID', v_total, 'CASH-' || v_order_number, now());
  insert into public.order_status_events(order_id, previous_status, new_status, actor_user_id)
  values (v_order_id, null, 'PLACED', v_user_id);
  v_token := public.create_collection_code(v_order_id);
  return jsonb_build_object('order_id', v_order_id, 'order_number', v_order_number, 'collection_token', v_token);
end;
$$;

create or replace function public.create_online_checkout(p_shop_id uuid, p_items jsonb, p_reservation_minutes integer default 15)
returns jsonb
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  v_user_id uuid := auth.uid();
  v_order_id uuid := gen_random_uuid();
  v_payment_id uuid := gen_random_uuid();
  v_order_number text := public.make_order_number();
  v_total numeric(12,2) := 0;
  v_item jsonb;
  v_menu public.menu_items%rowtype;
  v_qty integer;
  v_uni uuid;
  v_cafe uuid;
  v_transaction_ref text := 'SSL-' || upper(encode(gen_random_bytes(12), 'hex'));
  v_expires_at timestamptz := now() + make_interval(mins => greatest(p_reservation_minutes, 1));
begin
  if v_user_id is null or not public.has_role(v_user_id, 'customer') then raise exception 'Only authenticated customers can create checkouts'; end if;
  if jsonb_typeof(p_items) <> 'array' or jsonb_array_length(p_items) = 0 then raise exception 'Checkout must contain at least one item'; end if;

  select c.university_id, s.cafeteria_id into v_uni, v_cafe
  from public.shops s join public.cafeterias c on c.id = s.cafeteria_id join public.universities u on u.id = c.university_id
  where s.id = p_shop_id and s.is_active and s.approval_status = 'APPROVED' and c.is_active and c.approval_status = 'APPROVED' and u.is_active;
  if v_uni is null then raise exception 'Shop is not orderable'; end if;

  insert into public.orders(id, order_number, customer_id, university_id, cafeteria_id, shop_id, status, payment_method, total_amount)
  values (v_order_id, v_order_number, v_user_id, v_uni, v_cafe, p_shop_id, 'PAYMENT_PENDING', 'ONLINE', 0);

  for v_item in select * from jsonb_array_elements(p_items) loop
    v_qty := (v_item->>'quantity')::integer;
    select * into v_menu from public.menu_items where id = (v_item->>'menu_item_id')::uuid and shop_id = p_shop_id for update;
    if not found or not v_menu.is_active or not v_menu.is_manually_available then raise exception 'Menu item is unavailable'; end if;
    if v_qty is null or v_qty <= 0 or v_qty > v_menu.max_quantity_per_order then raise exception 'Invalid item quantity'; end if;
    if v_menu.stock_quantity - public.active_reserved_quantity(v_menu.id) < v_qty then raise exception 'Insufficient stock'; end if;
    insert into public.order_items(order_id, menu_item_id, item_name_snapshot, quantity, unit_price_snapshot, line_total_snapshot)
    values (v_order_id, v_menu.id, v_menu.name, v_qty, v_menu.price, v_qty * v_menu.price);
    insert into public.inventory_reservations(menu_item_id, order_id, payment_attempt_id, quantity, status, expires_at)
    values (v_menu.id, v_order_id, v_payment_id, v_qty, 'ACTIVE', v_expires_at);
    v_total := v_total + (v_qty * v_menu.price);
  end loop;

  update public.orders set total_amount = v_total where id = v_order_id;
  insert into public.payment_attempts(id, order_id, method, provider, status, amount, transaction_ref)
  values (v_payment_id, v_order_id, 'ONLINE', 'SSLCOMMERZ', 'PENDING', v_total, v_transaction_ref);
  insert into public.order_status_events(order_id, previous_status, new_status, actor_user_id)
  values (v_order_id, null, 'PAYMENT_PENDING', v_user_id);
  return jsonb_build_object('order_id', v_order_id, 'order_number', v_order_number, 'payment_attempt_id', v_payment_id, 'transaction_ref', v_transaction_ref, 'amount', v_total, 'expires_at', v_expires_at);
end;
$$;

create or replace function public.finalize_successful_online_payment(p_transaction_ref text, p_amount numeric, p_currency char(3), p_gateway_transaction_id text, p_gateway_metadata jsonb default '{}'::jsonb)
returns jsonb
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  v_payment public.payment_attempts%rowtype;
  v_order public.orders%rowtype;
  v_res public.inventory_reservations%rowtype;
  v_token text;
begin
  select * into v_payment from public.payment_attempts where transaction_ref = p_transaction_ref for update;
  if not found then raise exception 'Payment attempt not found'; end if;
  select * into v_order from public.orders where id = v_payment.order_id for update;
  if v_payment.status = 'PAID' then
    return jsonb_build_object('order_id', v_order.id, 'order_number', v_order.order_number, 'already_finalized', true);
  end if;
  if v_payment.method <> 'ONLINE' or v_payment.provider <> 'SSLCOMMERZ' or v_payment.status <> 'PENDING' then raise exception 'Payment attempt is not finalizable'; end if;
  if v_payment.amount <> p_amount or v_payment.currency <> p_currency then raise exception 'Payment amount or currency mismatch'; end if;
  if v_order.status <> 'PAYMENT_PENDING' then raise exception 'Order is not payment pending'; end if;

  for v_res in select * from public.inventory_reservations where payment_attempt_id = v_payment.id and order_id = v_order.id for update loop
    if v_res.status <> 'ACTIVE' or v_res.expires_at <= now() then raise exception 'Reservation is not active'; end if;
    update public.menu_items set stock_quantity = stock_quantity - v_res.quantity where id = v_res.menu_item_id and stock_quantity >= v_res.quantity;
    if not found then raise exception 'Insufficient stock during finalization'; end if;
    update public.inventory_reservations set status = 'CONSUMED', consumed_at = now() where id = v_res.id;
  end loop;

  update public.payment_attempts set status = 'PAID', paid_at = now(), gateway_transaction_id = p_gateway_transaction_id, gateway_metadata = p_gateway_metadata where id = v_payment.id;
  update public.orders set status = 'PLACED' where id = v_order.id;
  insert into public.order_status_events(order_id, previous_status, new_status, actor_user_id, metadata)
  values (v_order.id, 'PAYMENT_PENDING', 'PLACED', null, jsonb_build_object('payment_attempt_id', v_payment.id));
  v_token := public.create_collection_code(v_order.id);
  return jsonb_build_object('order_id', v_order.id, 'order_number', v_order.order_number, 'collection_token', v_token, 'already_finalized', false);
end;
$$;

create or replace function public.release_expired_reservations(p_payment_attempt_id uuid default null)
returns integer
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  v_count integer;
begin
  update public.inventory_reservations ir
  set status = 'EXPIRED', expired_at = now()
  where ir.status = 'ACTIVE'
    and (p_payment_attempt_id is null or ir.payment_attempt_id = p_payment_attempt_id)
    and ir.expires_at <= now();
  get diagnostics v_count = row_count;

  update public.payment_attempts pa
  set status = 'EXPIRED', expired_at = now()
  where pa.status = 'PENDING'
    and exists (select 1 from public.inventory_reservations ir where ir.payment_attempt_id = pa.id and ir.status = 'EXPIRED')
    and not exists (select 1 from public.inventory_reservations ir where ir.payment_attempt_id = pa.id and ir.status = 'ACTIVE');
  return v_count;
end;
$$;

create or replace function public.cancel_order(p_order_id uuid, p_reason text, p_restore_inventory boolean default false)
returns jsonb
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  v_user_id uuid := auth.uid();
  v_order public.orders%rowtype;
  v_item record;
begin
  if v_user_id is null then raise exception 'Authentication required'; end if;
  select * into v_order from public.orders where id = p_order_id for update;
  if not found then raise exception 'Order not found'; end if;
  if not public.is_active_shop_staff(v_user_id, v_order.shop_id) then raise exception 'Not authorized for this shop'; end if;
  if btrim(coalesce(p_reason, '')) = '' then raise exception 'Cancellation reason is required'; end if;
  if v_order.status not in ('PLACED', 'PREPARING') then raise exception 'Order cannot be cancelled from current status'; end if;

  if p_restore_inventory then
    for v_item in select menu_item_id, quantity from public.order_items where order_id = p_order_id loop
      update public.menu_items set stock_quantity = stock_quantity + v_item.quantity where id = v_item.menu_item_id;
    end loop;
  end if;

  update public.orders
  set status = 'CANCELLED', cancelled_at = now(), cancelled_by = v_user_id, cancellation_reason = p_reason, inventory_restored = p_restore_inventory
  where id = p_order_id;
  insert into public.order_status_events(order_id, previous_status, new_status, actor_user_id, reason, metadata)
  values (p_order_id, v_order.status, 'CANCELLED', v_user_id, p_reason, jsonb_build_object('inventory_restored', p_restore_inventory));
  update public.payment_attempts
  set refund_status = case when method = 'ONLINE' and status = 'PAID' then 'PENDING' else refund_status end,
      status = case when status = 'PENDING' then 'CANCELLED' else status end,
      cancelled_at = case when status = 'PENDING' then now() else cancelled_at end
  where order_id = p_order_id;
  return jsonb_build_object('order_id', p_order_id, 'status', 'CANCELLED');
end;
$$;

create or replace function public.validate_collection_qr(p_token text)
returns jsonb
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  v_user_id uuid := auth.uid();
  v_hash text := public.hash_collection_token(p_token);
  v_code public.collection_codes%rowtype;
  v_order public.orders%rowtype;
begin
  if v_user_id is null then raise exception 'Authentication required'; end if;
  select * into v_code from public.collection_codes where token_hash = v_hash for update;
  if not found then raise exception 'Invalid collection code'; end if;
  if v_code.used_at is not null then raise exception 'Collection code already used'; end if;
  if v_code.expires_at is not null and v_code.expires_at <= now() then raise exception 'Collection code expired'; end if;
  select * into v_order from public.orders where id = v_code.order_id for update;
  if v_order.status <> 'READY' then raise exception 'Order is not ready for collection'; end if;
  if not public.is_active_shop_staff(v_user_id, v_order.shop_id) then raise exception 'Not authorized for this shop'; end if;

  update public.orders set status = 'COLLECTED', collected_at = now(), collected_by = v_user_id where id = v_order.id;
  update public.collection_codes set used_at = now(), validated_by = v_user_id where id = v_code.id;
  insert into public.order_status_events(order_id, previous_status, new_status, actor_user_id)
  values (v_order.id, 'READY', 'COLLECTED', v_user_id);
  return jsonb_build_object('order_id', v_order.id, 'order_number', v_order.order_number, 'status', 'COLLECTED');
end;
$$;

create or replace function public.update_order_status(p_order_id uuid, p_new_status public.order_status)
returns jsonb
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  v_user_id uuid := auth.uid();
  v_order public.orders%rowtype;
begin
  if v_user_id is null then raise exception 'Authentication required'; end if;
  select * into v_order from public.orders where id = p_order_id for update;
  if not found then raise exception 'Order not found'; end if;
  if not public.is_active_shop_staff(v_user_id, v_order.shop_id) then raise exception 'Not authorized for this shop'; end if;
  if not ((v_order.status = 'PLACED' and p_new_status = 'PREPARING') or (v_order.status = 'PREPARING' and p_new_status = 'READY')) then
    raise exception 'Invalid order status transition';
  end if;
  update public.orders set status = p_new_status where id = p_order_id;
  insert into public.order_status_events(order_id, previous_status, new_status, actor_user_id)
  values (p_order_id, v_order.status, p_new_status, v_user_id);
  return jsonb_build_object('order_id', p_order_id, 'status', p_new_status);
end;
$$;

revoke all on function public.set_updated_at() from public, anon, authenticated;
revoke all on function public.has_role(uuid, public.role_name) from public, anon, authenticated;
revoke all on function public.is_admin(uuid) from public, anon, authenticated;
revoke all on function public.is_active_shop_staff(uuid, uuid) from public, anon, authenticated;
revoke all on function public.make_order_number() from public, anon, authenticated;
revoke all on function public.hash_collection_token(text) from public, anon, authenticated;
revoke all on function public.active_reserved_quantity(uuid) from public, anon, authenticated;
revoke all on function public.create_collection_code(uuid) from public, anon, authenticated;
revoke all on function public.create_cash_order(uuid, jsonb) from public, anon, authenticated;
revoke all on function public.create_online_checkout(uuid, jsonb, integer) from public, anon, authenticated;
revoke all on function public.finalize_successful_online_payment(text, numeric, char, text, jsonb) from public, anon, authenticated;
revoke all on function public.release_expired_reservations(uuid) from public, anon, authenticated;
revoke all on function public.cancel_order(uuid, text, boolean) from public, anon, authenticated;
revoke all on function public.validate_collection_qr(text) from public, anon, authenticated;
revoke all on function public.update_order_status(uuid, public.order_status) from public, anon, authenticated;

grant execute on function public.has_role(uuid, public.role_name) to authenticated;
grant execute on function public.is_admin(uuid) to authenticated;
grant execute on function public.is_active_shop_staff(uuid, uuid) to authenticated;
grant execute on function public.active_reserved_quantity(uuid) to authenticated;
grant execute on function public.hash_collection_token(text) to authenticated;
grant execute on function public.create_cash_order(uuid, jsonb) to authenticated;
grant execute on function public.create_online_checkout(uuid, jsonb, integer) to authenticated;
grant execute on function public.cancel_order(uuid, text, boolean) to authenticated;
grant execute on function public.validate_collection_qr(text) to authenticated;
grant execute on function public.update_order_status(uuid, public.order_status) to authenticated;
-- Payment finalization and reservation release are intended for trusted server/Edge contexts only.

alter table public.profiles enable row level security;
alter table public.roles enable row level security;
alter table public.user_roles enable row level security;
alter table public.universities enable row level security;
alter table public.cafeterias enable row level security;
alter table public.shops enable row level security;
alter table public.shop_staff_memberships enable row level security;
alter table public.menu_items enable row level security;
alter table public.orders enable row level security;
alter table public.order_items enable row level security;
alter table public.order_status_events enable row level security;
alter table public.payment_attempts enable row level security;
alter table public.inventory_reservations enable row level security;
alter table public.collection_codes enable row level security;

create policy profiles_select_self_or_admin on public.profiles for select to authenticated using (id = auth.uid() or public.is_admin(auth.uid()));
create policy profiles_update_self_or_admin on public.profiles for update to authenticated using (id = auth.uid() or public.is_admin(auth.uid())) with check (id = auth.uid() or public.is_admin(auth.uid()));

create policy roles_select_authenticated on public.roles for select to authenticated using (true);
create policy roles_admin_all on public.roles for all to authenticated using (public.is_admin(auth.uid())) with check (public.is_admin(auth.uid()));

create policy user_roles_select_self_or_admin on public.user_roles for select to authenticated using (user_id = auth.uid() or public.is_admin(auth.uid()));
create policy user_roles_admin_all on public.user_roles for all to authenticated using (public.is_admin(auth.uid())) with check (public.is_admin(auth.uid()));

create policy universities_public_read on public.universities for select to authenticated using (is_active or public.is_admin(auth.uid()));
create policy universities_admin_all on public.universities for all to authenticated using (public.is_admin(auth.uid())) with check (public.is_admin(auth.uid()));

create policy cafeterias_public_read on public.cafeterias for select to authenticated using ((is_active and approval_status = 'APPROVED' and exists (select 1 from public.universities u where u.id = university_id and u.is_active)) or public.is_admin(auth.uid()));
create policy cafeterias_admin_all on public.cafeterias for all to authenticated using (public.is_admin(auth.uid())) with check (public.is_admin(auth.uid()));

create policy shops_public_or_staff_read on public.shops for select to authenticated using ((is_active and approval_status = 'APPROVED' and exists (select 1 from public.cafeterias c join public.universities u on u.id = c.university_id where c.id = cafeteria_id and c.is_active and c.approval_status = 'APPROVED' and u.is_active)) or public.is_active_shop_staff(auth.uid(), id) or public.is_admin(auth.uid()));
create policy shops_admin_all on public.shops for all to authenticated using (public.is_admin(auth.uid())) with check (public.is_admin(auth.uid()));

create policy shop_staff_memberships_select_self_or_admin on public.shop_staff_memberships for select to authenticated using (user_id = auth.uid() or public.is_admin(auth.uid()) or public.is_active_shop_staff(auth.uid(), shop_id));
create policy shop_staff_memberships_admin_all on public.shop_staff_memberships for all to authenticated using (public.is_admin(auth.uid())) with check (public.is_admin(auth.uid()));

create policy menu_items_public_staff_admin_read on public.menu_items for select to authenticated using (exists (select 1 from public.shops s where s.id = shop_id and s.is_active and s.approval_status = 'APPROVED') or public.is_active_shop_staff(auth.uid(), shop_id) or public.is_admin(auth.uid()));
create policy menu_items_staff_admin_insert on public.menu_items for insert to authenticated with check (public.is_active_shop_staff(auth.uid(), shop_id) or public.is_admin(auth.uid()));
create policy menu_items_staff_admin_update on public.menu_items for update to authenticated using (public.is_active_shop_staff(auth.uid(), shop_id) or public.is_admin(auth.uid())) with check (public.is_active_shop_staff(auth.uid(), shop_id) or public.is_admin(auth.uid()));
create policy menu_items_staff_admin_delete on public.menu_items for delete to authenticated using (public.is_admin(auth.uid()));

create policy orders_select_owner_staff_admin on public.orders for select to authenticated using (customer_id = auth.uid() or public.is_active_shop_staff(auth.uid(), shop_id) or public.is_admin(auth.uid()));
create policy orders_admin_all on public.orders for all to authenticated using (public.is_admin(auth.uid())) with check (public.is_admin(auth.uid()));

create policy order_items_select_owner_staff_admin on public.order_items for select to authenticated using (exists (select 1 from public.orders o where o.id = order_id and (o.customer_id = auth.uid() or public.is_active_shop_staff(auth.uid(), o.shop_id) or public.is_admin(auth.uid()))));
create policy order_items_admin_all on public.order_items for all to authenticated using (public.is_admin(auth.uid())) with check (public.is_admin(auth.uid()));

create policy order_status_events_select_owner_staff_admin on public.order_status_events for select to authenticated using (exists (select 1 from public.orders o where o.id = order_id and (o.customer_id = auth.uid() or public.is_active_shop_staff(auth.uid(), o.shop_id) or public.is_admin(auth.uid()))));
create policy order_status_events_admin_insert on public.order_status_events for insert to authenticated with check (public.is_admin(auth.uid()));

create policy payment_attempts_select_owner_staff_admin on public.payment_attempts for select to authenticated using (exists (select 1 from public.orders o where o.id = order_id and (o.customer_id = auth.uid() or public.is_active_shop_staff(auth.uid(), o.shop_id) or public.is_admin(auth.uid()))));
create policy payment_attempts_admin_all on public.payment_attempts for all to authenticated using (public.is_admin(auth.uid())) with check (public.is_admin(auth.uid()));

create policy inventory_reservations_select_owner_staff_admin on public.inventory_reservations for select to authenticated using (exists (select 1 from public.orders o where o.id = order_id and (o.customer_id = auth.uid() or public.is_active_shop_staff(auth.uid(), o.shop_id) or public.is_admin(auth.uid()))));
create policy inventory_reservations_admin_all on public.inventory_reservations for all to authenticated using (public.is_admin(auth.uid())) with check (public.is_admin(auth.uid()));

create policy collection_codes_select_owner_admin on public.collection_codes for select to authenticated using (exists (select 1 from public.orders o where o.id = order_id and (o.customer_id = auth.uid() or public.is_admin(auth.uid()))));
create policy collection_codes_admin_all on public.collection_codes for all to authenticated using (public.is_admin(auth.uid())) with check (public.is_admin(auth.uid()));
